project_id = "nlrdiznleytpuwvugloi"

[functions.send-deal]
verify_jwt = false

[functions.send-verification]
verify_jwt = false

[functions.send-welcome]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false

[functions.track-email-click]
verify_jwt = false
